name: rop mvn build check integration test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - branch-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: clean disk
        if: steps.docs.outputs.changed_only == 'no'
        run: |
          df -h
          sudo swapoff /swapfile
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker images -q) -f
          df -h

      - name: rocketmq-impl test after build
        run: mvn test -DfailIfNoTests=false -pl tests

